import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "components/footer";
import Menu from "components/menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="flex flex-row flex-wrap justify-center justify-items-center w-screen"
          style={{ marginTop: "calc(32px + 32pt)"}}
        >
          {/* <Header links={[ {displayName: "About Me", href: "/about-me"} ]} logo="/next.svg" /> */}
          <Menu  />
          <div id="content-main">
            {children}
          </div>
        </div>
        <Footer links={[ {href: "/about-me", label: "About Me"} ]} logoSrc="/next.svg" />
      </body>
    </html>
  );
}
