import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "components/footer";
import Menu, { NavSection } from "components/menu";
import fs from 'fs/promises';
import path from 'path';
import { NotebookIndex } from "./ipynb/notebook";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const indexFile = await fs.readFile(path.join(process.cwd(), 'public', 'ipynb_index.json'), 'utf8');
  const index: NotebookIndex = JSON.parse(indexFile) as NotebookIndex;
  
  const navSections: NavSection[] = [
    {
      items: index
        .notebooks
        .filter(notebook => notebook.file.match(/^ipynb_pp\/pages\/.*.dnb$/))
        .map(notebook => ({
          href: `/pages/${notebook.slug}`,
          shortTitle: notebook['shortTitle'] as string || notebook.title,
        })),
      sectionHeader: 'Pages'
    },
    {
      items: index
        .notebooks
        .filter(notebook => notebook.file.match(/^ipynb_pp\/blogs\/.*.dnb$/))
        .map(notebook => ({
          href: `/blog/${notebook.slug}`,
          shortTitle: notebook['shortTitle'] as string || notebook.title,
        })),
      sectionHeader: 'Blog'
    },
  ];

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div
          className="flex flex-row flex-wrap xl:justify-start justify-center justify-items-center w-screen"
          style={{ marginTop: "calc(32px + 32pt)"}}
        >
          {/* <Header links={[ {displayName: "About Me", href: "/about-me"} ]} logo="/next.svg" /> */}
          <Menu sections={navSections} />
          <div id="content-main">
            {children}
          </div>
        </div>
        <Footer links={[ {href: "/about-me", label: "About Me"} ]} logoSrc="/next.svg" />
      </body>
    </html>
  );
}
